node {
   def commit_id
   stage('Preparation') {
     checkout scm
     bat "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'node') {
       bat 'npm install --only=dev'
       bat 'npm test'
     }
   }
   stage('docker build image') {
     docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
       def app = docker.build("nodejsappimage-image", '.')
     }
   }
   stage('docker images list') {
		bat 'docker --version'
		bat 'docker images'
     }

   stage('push image to jfrog artifactory'){
       bat 'docker login -u admin -p password 127.0.0.1:8081'
	bat 'docker tag nodejsappimage-image:${commit_id} 127.0.0.1:8081/docker-shubham/nodejsappimage-image:${commit_id}'
	bat 'docker push 127.0.0.1:8081/demodockerrepo/nodejsappimage-image:${commit_id}'
   }
}
